uploads = []
outputs = []

[[generated]]
id = "GJonICCywJdrHb09xaGYT"
uri = "file://client/public/images/hero-fishing.png"
type = "image"
title = "generated_image"

[[generated]]
id = "DwOCHT89TCKXHaVr87kqk"
uri = "file://attached_assets/generated_images/cover_desktop.png"
type = "image"
title = "desktop fishing cover"

[[generated]]
id = "GR3wSd8TyVKeKRkxATeU7"
uri = "file://attached_assets/generated_images/cover_mobile.png"
type = "image"
title = "mobile fishing cover"
